Added curl call to test the cloud function

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -46,6 +46,23 @@ jobs:
       env:
         FUNCTIONS_WORKER_RUNTIME: node
 
+    - name: Test Function App
+      run: |
+        for i in {1..10}
+        do
+          echo "Attempt $i to call the function..."
+          status_code=$(curl --write-out "%{http_code}" --silent --output /dev/null "https://create-documents-fa.azurewebsites.net/api/createhelloworldfile")
+          if [[ "$status_code" -eq 200 ]] ; then
+            echo "Successfully called the function!"
+            exit 0
+          else
+            echo "Failed to call the function. Status code: $status_code"
+            sleep 15  # wait for 15 seconds before retrying
+          fi
+        done
+        echo "Failed to call the function after $i attempts"
+        exit 1
+
     - name: Terraform Destroy
       if: always()
       env:
